### ISSUE TITLE
EDDI not starting/not connecting to Companion App

### ISSUE THREAD

**Issue by Darkcyde13** [cmdrmcdonald/EliteDangerousDataProvider#122]
Hi,

I was using EDDI perfectly fine last night, no problems at all.  Today when I tried to start EDDI, it tries to load, but does not appear.  After a bit of trouble shooting (deleting credentials.json) it seems there is a problem with connecting to the Companion App.

After deleting the credentials, EDDI loads up.  When I try to reconnect to the Companion App, it throws the following error:

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at EddiCompanionAppService.CompanionAppService.AugmentShipInfo(Ship ship, List`1 storedShips)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(JObject json)
   at EddiCompanionAppService.CompanionAppService.ProfileFromJson(String data)
   at EddiCompanionAppService.CompanionAppService.Profile(Boolean forceRefresh)
   at Eddi.MainWindow.companionAppNextClicked(Object sender, RoutedEventArgs e)
```
If I close EDDI, it then will not start again until I've deleted the credentials.json.  This is on beta 3, I also tried going back to beta 2, but it's the same.  Would I be right in thinking this is a problem with the Companion App, and as such nothing you can do?

**Comment by cmdrmcdonald** [comment]
This is an error in -b3 that caused NULL entries to be written to the ships.json file.  I've released -b4 that has a fix for this, but you should remove the NULL entry from the ships.json after you upgrade (and before as well, if EDDI isn't starting).

**Comment by Darkcyde13** [comment]
Thanks for your reply.  I've upgraded to beta 4, but it's still happening.  I've deleted the ships.json and EDDI starts fine.  I've been able to log back into the Companion App and it repopulates my ship yard.  All works fine until I quit EDDI, it then doesn't start up again.  I looked at the new ships.json and the null entry is back at the end of the file.

This is a fresh copy of my ships.json after deleting it and reloading EDDI:
```
{
  "ships": [
    {
      "LocalId": 11,
      "name": null,
      "phoneticname": null,
      "role": "Multi-purpose"
    },
    {
      "LocalId": 2,
      "name": null,
      "phoneticname": null,
      "role": "Multi-purpose"
    },
    {
      "LocalId": 0,
      "name": null,
      "phoneticname": null,
      "role": "Multi-purpose"
    },
    {
      "LocalId": 1,
      "name": null,
      "phoneticname": null,
      "role": "Multi-purpose"
    },
    {
      "LocalId": 3,
      "name": null,
      "phoneticname": null,
      "role": "Multi-purpose"
    },
    {
      "LocalId": 4,
      "name": null,
      "phoneticname": null,
      "role": "Multi-purpose"
    },
    {
      "LocalId": 5,
      "name": null,
      "phoneticname": null,
      "role": "Multi-purpose"
    },
    {
      "LocalId": 6,
      "name": null,
      "phoneticname": null,
      "role": "Multi-purpose"
    },
    {
      "LocalId": 7,
      "name": null,
      "phoneticname": null,
      "role": "Multi-purpose"
    },
    {
      "LocalId": 8,
      "name": null,
      "phoneticname": null,
      "role": "Multi-purpose"
    },
    {
      "LocalId": 9,
      "name": null,
      "phoneticname": null,
      "role": "Multi-purpose"
    },
    {
      "LocalId": 10,
      "name": null,
      "phoneticname": null,
      "role": "Multi-purpose"
    },
    {
      "LocalId": 0,
      "name": null,
      "phoneticname": null,
      "role": null
    }
  ]
}
```

When I start EDDI after deleting the ships.json, and go look at my ship yard, there is a blank entry at the bottom.  I'm guessing this is the culprit creating a null entry in the ships.json file.

**Comment by Tkael** [comment]
I'm getting the same error in my log as the OP and can confirm that the null entry is still being written to ships.json in beta -b4. I've tried both removing the .json file and editing the .json file, but the null entry keeps getting re-written.

{
  "ships": [
    {
      "LocalId": 6,
      "name": "the Windblown Leaf",
      "phoneticname": null,
      "role": "Exploration"
    },
    {
      "LocalId": 0,
      "name": "Ragnarök",
      "phoneticname": null,
      "role": "Multi-purpose"
    },
    {
      "LocalId": 11,
      "name": "Atremis",
      "phoneticname": null,
      "role": "Bounty hunting"
    },
    {
      "LocalId": 12,
      "name": "Prospector",
      "phoneticname": "prəsˈpɛktə",
      "role": "Mining"
    },
    {
      "LocalId": 13,
      "name": "Serenity",
      "phoneticname": null,
      "role": "Mining"
    },
    {
      "LocalId": 14,
      "name": "Sovingaard",
      "phoneticname": null,
      "role": "Multi-purpose"
    },
    {
      "LocalId": 16,
      "name": "the Bird of Prey",
      "phoneticname": "ðəbɜːdɒvpreɪ",
      "role": "Combat"
    },
    {
      "LocalId": 19,
      "name": "Mischief",
      "phoneticname": null,
      "role": "Multi-purpose"
    },
    {
      "LocalId": 0,
      "name": null,
      "phoneticname": null,
      "role": null
    }
  ]
}

EDDI does not start unless I first delete the entry:
    {
      "LocalId": 0,
      "name": null,
      "phoneticname": null,
      "role": null
    }
and even after I delete the entry EDDI does not say "hello" or "goodbye" when entering or exiting EDDI... Ships.json appears to be getting updated to include the null entry every time that the VA plugin or EDDI.exe is started.

**Comment by Darkcyde13** [comment]
I also noticed that EDDI doesn't say 'Goodbye' anymore.  I just thought Cmdr. McDonald had decided to remove it.

**Comment by cmdrmcdonald** [comment]
I've just pushed 2.1.1-b5 which should clean up the ships.json automatically and allow it to operate.

And yeah, I removed the 'goodbye' bit because it didn't do a lot other than delay the shutdown of EDDI and it caused confusion when EDDI auto-restarted after an upgrade.

**Comment by Darkcyde13** [comment]
Yes, this fix works perfectly. Thank you!

**Comment by cmdrmcdonald** [comment]
This is fixed in release 2.2.0.
