### ISSUE TITLE
After updating EDDI, Frontier API not connecting

### ISSUE THREAD

**Issue by carlostib** [cmdrmcdonald/EliteDangerousDataProvider#286]
Hi,
I just upgraded to EDDI 2.3.1 to be used with ED 2.4 The Return update, and now the Frontier API is not connecting with my credentials. I entered the received code into the EDDI app, and still is not connecting, is this a known issue with EDDI 2.3.1 or what solution can I have for this?. Thanks.

**Comment by Tkael** [comment]
it's not just EDDI. apparently FDev mucked up the API a bit during the update. hopefully should be fixed soon

**Comment by Tkael** [comment]
There's a bug report about this on the forums: & developers are pinging FDev on Discord for a fix https://forums.frontier.co.uk/showthread.php/378874-cAPI-asking-user-to-purchase-ED

**Comment by SJForrest** [comment]
Still not working, not only for EDDI, for ED marketconnector too.

**Comment by icextend** [comment]
Same issue here

**Comment by FireSammy** [comment]
Cannot connect EDDI API 2.3.1

**Comment by Tkael** [comment]
FDev have raised this bug to the highest priority (see prior linked bug report)

**Comment by Stevax** [comment]
Patch notes today say API fixed but still not able to successfully enter authorisation code.

**Comment by AndySpawn** [comment]
Just tried it there now.  Working for me.  Version: 2.4.0-b4

**Comment by rosscarlson** [comment]
Still not working for me - same error that I don't have access to the API.  This is after confirming my password and getting the auth key.

**Comment by Tkael** [comment]
Likewise. But others report they are able to connect. I'll re-attempt this evening.

**Comment by JTonyC** [comment]
Same here unfortunately. Mine was clean install - Confirm my password, get the auth key, paste that in, then:

Unable to log in. This is usually a temporary issue with Frontiers servvice; please try again later

Version: 2.3.1

Upgraded to 2.4.0-b4 - Same deal :(

**Comment by FireSammy** [comment]
Working now!!

**Comment by Tkael** [comment]
good to know. I was also able to reconnect today
